### ISSUE TITLE
confusion matrix just on training data?

### ISSUE THREAD

**Issue by azbones** [azbones/cis503_machine_learning#2]
In the machine learning intro there is a confusion matrix right after the KNN model is trained. What is it testing against?  It seems like this is confusing unless we have a training and test dataset.

**Comment by azbones** [comment]
I think it is bootstrapping the data, but that is still not a great intro concept...

**Comment by nirmalpatel** [comment]
Oh, I see, the confusion matrix is produced by doing 25 random train/test
splits. That is done automatically by caret.



I thought I had put a confusion matrix in K-Means, but that is not the case.
